version: '3.8'

services:
  mantis:
    image: vimagick/mantisbt
    restart: always
    ports:
      - "80:80"
    environment:
      DB_TYPE: sqlite
      DB_NAME: /data/mantis.db
    volumes:
      - mantis_data:/data

volumes:
  mantis_data: