version: '3.8'

services:
  mantis:
    image: vimagick/mantisbt
    restart: always
    ports:
      - "80:80"  # <- puerto público
    environment:
      DB_TYPE: mysqli
      DB_HOST: mysql.railway.internal
      DB_NAME: railway
      DB_USER: root
      DB_PASSWORD: wapQVAmqRtABsoRrdWLQwMZwdwIxvNtT